Add Href to found-a-bug
kettingpowered/Site pull request #5
Opened 2024-04-11 23:56 UTC by wolflord212312

Reason so people can click github page and get directed to keettingpowered github and from there go to create a ISSUE

2024-04-11 23:57 UTC, wolflord212312 commented
Did NOT Link to a specific repo as one can not be sure if its a launcher issue or a game issue 🤷 
So Deal with it or fight over it
I help? +

2024-04-12 00:19 UTC, wolflord212312 commented
Will say red lost me about this "safe answer []()"

then said there should be safe somewhere in this file that was used, Cant Find what he is talking about in this file 

I am unsure what he is saying, Gonna leave it as is

2024-04-12 07:08 UTC, C0D3-M4513R requested changes

2024-04-12 07:08 UTC, C0D3-M4513R commented on src/data/faq/questions.js
> +        answer: "Go to our <a href='${global.githubUrl}'>github page</a> and create an issue in the correct repository."
There is no safe answer

2024-04-12 07:15 UTC, C0D3-M4513R commented on src/data/faq/questions.js
> +        answer: "Go to our <a href='${global.githubUrl}'>github page</a> and create an issue in the correct repository."
Also please redirect to Ketting here. 99% of the issues belong there.
For that 1%, we can always move them to the correct repo.

2024-04-12 07:25 UTC, C0D3-M4513R commented
Superseded by: #6

2024-04-12 07:25 UTC, closed without merging

2024-04-12 07:53 UTC, C0D3-M4513R commented
nvm. We apparently cannot use global or app in that context.